### ISSUE TITLE
No publishable connections found

### ISSUE THREAD

**Issue by jomiguelcarv** [nicolaasburgers/definition-library-releases#27]
Followed the instructions for both Github and Grasshopper setup. When clicking on "Publish", I get a popup saying "No publishable connections found." What can this mean?

**Comment by nicolaasburgers** [comment]
This usually means that there aren't any repositories in your list for which you have GitHub "push" (write) permissions.  Is your GitHub account either the owner, or has it been added as a collaborator, of at least one repository in your list?

I'm happy to schedule a live problem-solving call if that will help - you can schedule one at work.nicolaas@gmail.com between 9am and 8pm AEDT.
